#
# Note:  To include plugins, set the environment variable 'plugins' to be
# a space-separated list chosen from the names of the folders under ./plugins, e.g.
# "plugins=oauth dicom_viewer"
# 
#
---
version: "3"
services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017"
    volumes:
      - "/data/db"

  girder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        plugins: $plugins
    ports:
      - "8080:8080"
    links:
      - "mongodb:mongodb"
    command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder
